# Generated by Django 4.2.6 on 2023-10-11 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='popularity_source',
            new_name='popularity_score',
        ),
    ]
